from typing import Protocol, TypedDict
from datetime import datetime


class Service(TypedDict):
    ip: str
    name: str
    expire_at: datetime

class BaseDB(Protocol):
    def set(self, service: Service): ...
    def get(self, name: str) -> Service | None: ...
    def remove(self, name: str): ...
    def get_all(self) -> list[Service]: ...
    def remove_all(self, names: list[str]): ...